// <auto-generated />
using System;
using DWC_NightOwlProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DWCNightOwlProject.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20230227050754_name=AppConnection")]
    partial class nameAppConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DWC_NightOwlProject.Data.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Completion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TemplateID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserID");

                    b.Property<int>("WorldId")
                        .HasColumnType("int")
                        .HasColumnName("WorldID");

                    b.HasKey("Id")
                        .HasName("PK__Material__3214EC2785581C70");

                    b.HasIndex(new[] { "TemplateId" }, "IX_Material_TemplateID");

                    b.HasIndex(new[] { "WorldId" }, "IX_Material_WorldID");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("DWC_NightOwlProject.Data.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK__Template__3214EC27F3675E38");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("DWC_NightOwlProject.Data.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__World__3214EC27495DB421");

                    b.ToTable("World");
                });

            modelBuilder.Entity("DWC_NightOwlProject.Data.Material", b =>
                {
                    b.HasOne("DWC_NightOwlProject.Data.Template", "Template")
                        .WithMany("Materials")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("Material_Fk_Template");

                    b.HasOne("DWC_NightOwlProject.Data.World", "World")
                        .WithMany("Materials")
                        .HasForeignKey("WorldId")
                        .IsRequired()
                        .HasConstraintName("Material_Fk_World");

                    b.Navigation("Template");

                    b.Navigation("World");
                });

            modelBuilder.Entity("DWC_NightOwlProject.Data.Template", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DWC_NightOwlProject.Data.World", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
